### ISSUE TITLE
Road to Mesh2HRTF v1.1.2

### ISSUE THREAD

**Issue by f-brinkmann** [Any2HRTF/Mesh2HRTF#126]
Handeld in #127

- [x] Finish #124 
- [x] Finish #125 
- [x] Test updates in develop
- [x] Improve tests to work with latest Blender and pyfar versions (#128)
- [x] Add and test version in mesh2hrtf Python API (#111)
- [x] Finish #108
- [x] Update HRTF Tutorial for Blender 4.0 #129
